version: '2'
services:
  db:
    build: './magento-baza-danych'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
    ports:
      - "3306:3306"
    networks:
      - default
    volumes:
      - ./mysql/data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_HOST=db
     - PMA_USER=root
     - PMA_PASSWORD=root
     - MYSQL_ROOT_PASSWORD=root
    ports:
      - "8080:80"
  apache:
    build: './RebisShop-www'
    volumes:
      - ./RebisShop-www/RebisShop/:/var/www/html/
    depends_on:
      - db
    ports:
      - "80:80"
    links:
      - db
    networks:
      - default