version: '2'
services:
  db:
    image: mariadb
    build: './magento-baza-danych'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
    ports:
      - 3306:3306
    networks:
      - rebis-network
    volumes:
      - ./mysql/data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_HOST=db
     - PMA_USER=root
     - PMA_PASSWORD=root
     - MYSQL_ROOT_PASSWORD=root
    ports:
      - 8080:80
    networks:
      - rebis-network
  apache:
    build: './RebisShop-www'
    volumes:
      - ./RebisShop-www/RebisShop/:/var/www/html/
    depends_on:
      - db
    ports:
      - 80:80
    links:
      - db
    networks:
      - rebis-network
  redis:
    image: redis
    ports:
     - 6379
    networks:
      - rebis-network

  redis-session:
    image: redis
    ports:
     - 6379
    networks:
      - rebis-network

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - rebis-network

networks:
  rebis-network:
    driver: bridge

volumes:
  dbdata:
    driver: bridge